name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Docker Lint
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3.1.0
      
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
  
  build:
    uses: ./docker-release.yml

  scan:
    uses: ./docker-scan.yml