name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Docker Lint
    uses: crushten/github_workflow_repo/.github/workflows/docker_lint.yml@main
  
  build:
    name: Docker Build
    needs: lint
    uses: crushten/github_workflow_repo/.github/workflows/docker_build.yml@main

  scan:
    name: Docker Scan
    needs: build
    uses: crushten/github_workflow_repo/.github/workflows/docker_scan.yml@main